### ISSUE TITLE
failed due to: exit code(128)

### ISSUE THREAD

**Issue by bvansambeek** [rbray89/hassio-addons#3]
ERROR (MainThread) [hassio.addons.git] Can't clone https://github.com/rbray89/hassio-addons/tree/master/openvpn_server repository: Cmd('git') failed due to: exit code(128)
  cmdline: git clone --depth=1 --recursive --shallow-submodules -v https://github.com/rbray89/hassio-addons/tree/master/openvpn_server /data/addons/git/333f0fce
  stderr: 'Cloning into '/data/addons/git/333f0fce'...
fatal: repository 'https://github.com/rbray89/hassio-addons/tree/master/openvpn_server/' not found

This part is from my Hassio system log.
I am unable to install this addon, would be nice! Thanks for the work!

System	Resin OS 2.3.0+rev1
Hass.io supervisor version 140

**Comment by rbray89** [comment]
You should be able to add the repo now. Was missing the repository.json file.
