### ISSUE TITLE
DNS address is local, running PiHole

### ISSUE THREAD

**Issue by SamJongenelen** [rbray89/hassio-addons#4]
Hey, nice addon! I'd like to try this, but i am indeed running PiHole on the same device as I intend to run the OpenVPN server. The readme states this might give issues regarding DNS for the VPN clients.

A couple of questions
- Any progress on this? :)
- Would be using the non local address be an option? _E.G. using 192.168.1.10_ ? Mind you, performance is not an issue

**Comment by rbray89** [comment]
I've tried a variety of things, ranging from going to/from host network on the container, doing the same for the pihole container, permissions, etc. My current thinking is that when traffic pops up out of the host tunnel, and contacts the local DNS service, it doesn't have a route back (the route back is only established on outgoing traffic to the rest of the network?) but I'd need to read up on how tunnels establish routes to be sure. I found this to be an issue when I setup my router to advertise my HassOS instance as a DNS server, and found that my HassOS instance couldn't resolve addresses. Had to setup a config to go directly to external servers, so it isn't limited to this addon.

There *may* be two workarounds we can use though.
1) Use the local IPv6 address for DNS. I think this might be able to route the traffic properly, but I'm not certain. (untested)
2) Use a separate box for PiHole. (this should work, I can reach other entities off the vlan just fine.

**Comment by SamJongenelen** [comment]
Ok, im trying it tomorrow. Maybe your pihole did not allow request from your containers? I had to make a change to the default behaviour iirc

**Comment by sdesalve** [comment]
@rbray89 have you tried this? (See final config)

https://marcstan.net/blog/2017/06/25/PiVPN-and-Pi-hole/

**Comment by rbray89** [comment]
@sdesalve this is quite helpful! Looks like I need the pi-hole addon to provide a way to specify multiple interfaces to bind on though. Filed a PR [here](https://github.com/hassio-addons/addon-pi-hole/issues/68)

**Comment by sdesalve** [comment]
> @sdesalve this is quite helpful! Looks like I need the pi-hole addon to provide a way to specify multiple interfaces to bind on though. Filed a PR [here](https://github.com/hassio-addons/addon-pi-hole/issues/68)
please try following:

In your add-on edit config and leave only this DNS:
  "dns": [
    "10.8.0.1"
  ]
![2](https://user-images.githubusercontent.com/9841662/52840450-99647b80-30f9-11e9-8a3d-fc5195cc7ffd.png)

Using this add-on; https://community.home-assistant.io/t/community-hass-io-add-on-pi-hole/33817?u=frenck

check option: "Listen on all interfaces, permit all origins"... 
![1](https://user-images.githubusercontent.com/9841662/52840448-98cbe500-30f9-11e9-807c-f6af489621e0.png)

Shoud now working...

**Comment by rbray89** [comment]
Using ad guard also seems to allow usage of local DNS resolution.
