### ISSUE TITLE
Install failure on amd64 arch

### ISSUE THREAD

**Issue by G4rpez** [rbray89/hassio-addons#9]
Hi, got this error and installation fails:
`20-01-12 06:45:57 INFO (SyncWorker_8) [hassio.docker.addon] Start build 572f9090/aarch64-addon-openvpn_server:0.1.66
20-01-12 06:47:20 ERROR (SyncWorker_8) [hassio.docker.addon] Can't build 572f9090/aarch64-addon-openvpn_server:0.1.66: The command '/bin/ash -o pipefail -c apk add --no-cache -U --virtual .build-deps         build-base         wget         git 	go  && apk add --update -U --no-cache         jq         bc         libressl         iptables         ip6tables         openvpn  && go get -u github.com/quantumew/mustache-cli  && cp $GOPATH/bin/* /usr/local/bin/  && rm -rf $GOPATH  && wget https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.5/EasyRSA-nix-3.0.5.tgz -O ~/easyrsa.tgz  && apk del .build-deps' returned a non-zero code: 2`

**Comment by rogerone75** [comment]
Hi, I have the same problem... please can you help me?

**Comment by memone75** [comment]
Hi, same error, but on a different arch:

`20-03-10 14:26:12 ERROR (SyncWorker_9) [supervisor.docker.addon] Can't build 572f9090/armv7-addon-openvpn_server:0.1.66: The command '/bin/ash -o pipefail -c apk add --no-cache -U --virtual .build-deps         build-base         wget         git 	go  && apk add --update -U --no-cache         jq         bc         libressl         iptables         ip6tables         openvpn  && go get -u github.com/quantumew/mustache-cli  && cp $GOPATH/bin/* /usr/local/bin/  && rm -rf $GOPATH  && wget https://github.com/OpenVPN/easy-rsa/releases/download/v3.0.5/EasyRSA-nix-3.0.5.tgz -O ~/easyrsa.tgz  && apk del .build-deps' returned a non-zero code: 2`

**Comment by koslovsky** [comment]
Hello, I have the same problem... please can you help me? @rogerone75 @memone75 @G4rpez ?

**Comment by bubez81** [comment]
sadly same problem here on a raspberry 4

**Comment by rbray89** [comment]
I think these issues should be fixed in the latest version.
